name: Build and Push Docker Image

on:
  push:
    tags:
      - '*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        env:
          IMGAE_TAG: ${{ env.GIT_TAG }}
        run: |
          docker build -t lookoutking/image-ocr:$IMGAE_TAG .
          docker push lookoutking/image-ocr:$IMGAE_TAG
